### ISSUE TITLE
not working and incress ms 

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qb-commandbinding#2]
When using this script
and add /binds
With dpemote
does not work 
There is a problem that needs to be fixed
try this
box1: E box2:HANDSUP
not working

and more incress ms 6

**Comment by JericoFX** [comment]
i tested and the binds resources never go up, and the other problem is the dp emotes, you can use nums

**Comment by vanillla1** [comment]
Have you tried the following?
/binds
box1 E
box2 HANDSUP

not work
@JericoFX

**Comment by vanillla1** [comment]
In the default project qbcore
working fine with script animations
@JericoFX
