### ISSUE TITLE
What is the benefit of this script?

### ISSUE THREAD

**Issue by vanillla1** [qbcore-framework/qb-commandbinding#4]
What is the benefit of this script?
If it does not work with dpemote 

When using this script
and add /binds
With dpemote
does not work
There is a problem that needs to be fixed
try this
box1: E box2:HANDSUP
not working

**Comment by JericoFX** [comment]
maybe you dont use it, but a lot of people like this script, dpemotes isnt the only resource, you can create a comand and bind it.

**Comment by vanillla1** [comment]
Yes Yes
I play on a lot of servers
We work a lot on binds with animation

**Comment by vanillla1** [comment]
Look, I took permission from someone who created a new file
He told me I don't have any free time
To complete the project
The project is binds with json
He told me if you want to complete it and publish it, do so
https://github.com/vanillla1/qb-commandbinds
look this
Based on same menu qb-bossmenu
@JericoFX

**Comment by BerkieBb** [comment]
The reason why dpemotes's commands don't work is because only qbcore created commands can be triggered, if you don't like that then don't use it or leave a suggestion
