### ISSUE TITLE
Only works with some commands

### ISSUE THREAD

**Issue by Cappinator** [qbcore-framework/qb-commandbinding#6]
I have a weird issue.  It's only working with some commands.
/mask used manually works, "mask" as bind doesn't work.
/escort used manually works, "escort" as bind works.

I can't figure out what's going wrong

**Comment by ihyajb** [comment]
The bind menu currently only works with `QBCore.Commands.Add` commands, not `RegisterCommand`

## Below is an image with *some* of the commands that the bind menu supports

![image](https://user-images.githubusercontent.com/66404074/129458662-29b8e2e7-ad7c-470f-a845-899a896354a9.png)
