### ISSUE TITLE
Cannot bind commands

### ISSUE THREAD

**Issue by P4R4NORM4L** [qbcore-framework/qb-commandbinding#8]
Why is it so hard to rebind commands?

I've disabled this script because I thought it was overriding the radial menu F1

I've looked through the code of radial menu to change the keybind to middle mouse button which is in the file

/resources/[qb]/qb-radialmenu/client
on line 8

`RegisterKeyMapping('radialmenu', 'Open Radial Menu', 'mouse_button', 'MOUSE_MIDDLE') --'keyboard', 'F1'`

It just reverts the keymapping back to default
what is causing this issue?

why can't the keybindings be in the config like normal scripts
I think we should have the option to change the bindings on all commands as we see fit.

I feel like everyone needs a bachelor's degree in computer science in order to make this work
I hope someone can help me understand

Where are the Wikis?

Have a nice day :)

**Comment by Scott1sh** [comment]
> Why is it so hard to rebind commands?
> 
> I've disabled this script because I thought it was overriding the radial menu F1
> 
> I've looked through the code of radial menu to change the keybind to middle mouse button which is in the file
> 
> /resources/[qb]/qb-radialmenu/client
> on line 8
> 
> `RegisterKeyMapping('radialmenu', 'Open Radial Menu', 'mouse_button', 'MOUSE_MIDDLE') --'keyboard', 'F1'`
> 
> It just reverts the keymapping back to default
> what is causing this issue?
> 
> why can't the keybindings be in the config like normal scripts
> I think we should have the option to change the bindings on all commands as we see fit.
> 
> I feel like everyone needs a bachelor's degree in computer science in order to make this work
> I hope someone can help me understand
> 
> Where are the Wikis?
> 
> Have a nice day :)

Change the keybind in your FiveM settings in the ESC menu, as its already set once you log into your server
